### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by RangerMauve** [sindresorhus/pretty-ms#13]
It'd be nice if there was a way to specify the strings used for the hours/dates/minutes/etc. so that other languages could work with this module.

**Comment by RangerMauve** [comment]
Mostly, it'd be nice if we configure things in a similar way to [human-interval](https://www.npmjs.com/package/human-interval)

**Comment by RangerMauve** [comment]
Would a PR be welcome?

**Comment by sindresorhus** [comment]
No thanks. I would prefer to keep this module simple.

**Comment by vaidd4** [comment]
Hey @RangerMauve,
I made a gist for custom time units : 
https://gist.github.com/vaidd4/0d83ddba3fb218bb2a7949a4b93ee686

It just adds an optional parameter `units`. it's not the best implementation but will surely satisfy basic needs for other languages.

**Comment by RangerMauve** [comment]
@vaidd4 Could you publish it as a module which depends on pretty-ms so that it'd be easier for people to use? Maybe call it something like `localized-pretty-ms`?

**Comment by vaidd4** [comment]
@RangerMauve thanks for the interest, I may try to do so this week-end.
But this gist is far from an ideal alternative for this module to get localized units.

Hi @sindresorhus , would you consider adding personalized units (instead of complete localization) ? (you can look at my gist for some inspiration)

**Comment by sindresorhus** [comment]
@vaidd4 Sorry no, I don't want to complicate it. Localization also doesn't always work directly 1:1. So in some cultures, there would be a need for something more advanced. I just don't want to deal with this.
