### ISSUE TITLE
Add support for years

### ISSUE THREAD

**Issue by lykmapipo** [sindresorhus/pretty-ms#16]
```js
var prettyMs = require('pretty-ms');
prettyMs(133700000000);

//"1547d 10h 53m 20s"
```

Days should be in year at least

**Comment by sindresorhus** [comment]
Months and years depend on when you're calculating. Do you want the months and year when it's calculated or when the ms number was produced? Those might be different. That's why I didn't add it initially, since month and year can be different depending on when it's calculated.

**Comment by sindresorhus** [comment]
I've been thinking about this and I'm ok with adding the year here, but not months. We can assume 365 days as it's just an estimation anyways. So `1547d 10h 53m 20s` would become `4y 87d 10h 53m 20s`.
