### ISSUE TITLE
publishing es6 code?

### ISSUE THREAD

**Issue by contra** [sindresorhus/pretty-ms#18]
Not sure if this was intentional, but this breaks uglify and a bunch of other tools.

We updated pretty-ms to 3.0 and it broke our builds. Would also make a bunch of browsers incompatible.

**Comment by kevva** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

You want the ES2015 compatible version of Uglify: https://www.npmjs.com/package/uglify-es, or you need to use Babel on your dependencies, see https://github.com/SamVerschueren/babel-engine-plugin.

**Comment by contra** [comment]
Okay, can't say I agree with that but it is your library so you do what you want. Hope you reconsider in the future.
