### ISSUE TITLE
Don't strip `.0`-suffix when `secDecimalDigits` is set to `1`

### ISSUE THREAD

**Issue by rexxars** [sindresorhus/pretty-ms#20]
I find it kind of confusing that specifying `secDecimalDigits: 1` and formatting `1000` will lead to `1s`. If I'm specifying that I want one decimal, I don't feel like stripping the decimal point makes sense. Especially since it seems that specifying `secDecimalDigits: 2` will show `.00`.

Is this a concious decision, or an oversight, or somewhere between? :)
Thoughts?

**Comment by kevva** [comment]
If `secDecimalDigits: 2` shows `.00` it definitely sounds like a bug. They should have the same behaviour.

**Comment by rexxars** [comment]
This line:
```
const secStr = sec.toFixed(secDecimalDigits).replace(/\.0$/, '');
```
As it only has a single `0` and no `+` on the end, it'll just remove it if it is a single digit. I'll see if I can find the time to send a PR at some point if no one else gets to it before me.

**Comment by rexxars** [comment]
@sindresorhus Would you accept a PR that takes an option to keep the decimals on whole numbers? I'm using this library for a progress indicator thingy which keeps updating the time spent every ~60ms or so, and it keeps flickering in the terminal when it hits a whole number - I'd prefer if it just kept the fixed length as specified.

**Comment by htbkoo** [comment]
hi @rexxars just curious if you still plan to create the PR for taking the option to keep the decimals on whole numbers?
It sounds like a useful feature that would make the library more flexible.
Please let me know if I can help though :)

And thanks for creating this handy package, @sindresorhus !

**Comment by rexxars** [comment]
@htbkoo https://github.com/sindresorhus/pretty-ms/pull/22

**Comment by ulken** [comment]
> @sindresorhus Would you accept a PR that takes an option to keep the decimals on whole numbers? I'm using this library for a progress indicator thingy which keeps updating the time spent every ~60ms or so, and it keeps flickering in the terminal when it hits a whole number - I'd prefer if it just kept the fixed length as specified.

@sindresorhus For the same reason, I would find it preferable if sub-seconds could be output as seconds. I.e. `900ms` -> `0.9s`. Right now I'm wrapping `pretty-ms` and adding the logic myself, but does it qualify for an option to be included in the library?
