### ISSUE TITLE
SecDecimalDigits Rollover Bug

### ISSUE THREAD

**Issue by FireController1847** [sindresorhus/pretty-ms#26]
Sorry, it would have been a long title if I explained it any better lol.

Basically, let's say you have a time that's 2 minutes 59.7 seconds (or `179700` milliseconds). When using `secDecimalDigits: 0`, I'd assume it rounds the last number. By rounding 59.7, though, it results in 60. I'd assume that pretty-ms would handle the 60 rollover and say three minutes. And that's the bug: it doesn't.

**Reproduceable Code**
```js
const pms = require("pretty-ms");
console.log(pms(179700, { verbose: true, secDecimalDigits: 0 }));
// Results in 2 minutes 60 seconds
// Should be 3 minutes
```

**Comment by icyflame** [comment]
This also happens with any other rollover, not just seconds. Choosing a value 1 ms less than a whole value leads to this problem.

```
# 1 ms less than a year
> m(365*24*3600*1e3 - 1)
'364d 23h 60m 0s'
# 1 ms less than a day
> m(24*3600*1e3 - 1)
'23h 60m 0s'
# 1 ms less than an hour
> m(3600*1e3 - 1)
'60m 0s'
# 1 ms less than 2 hours
> m(2*3600*1e3 - 1)
'1h 60m 0s'
```

**Comment by kolyaventuri** [comment]
I was able to reproduce the error, I'll take a look into it and submit a PR if that's alright?

```
node --version
> v8.9.3

npm --version
> 5.5.1

parse-ms version (3.2.0)
```

**Comment by kolyaventuri** [comment]
PR #27 fixes this
