### ISSUE TITLE
Refactor to be more in line with SRP

### ISSUE THREAD

**Issue by kolyaventuri** [sindresorhus/pretty-ms#28]
Currently the package is defined in a single index.js file. Though it is a small package, it could be refactored to clean up the codebase and be more in line with single responsibility principles. For instance, there are some nested ternaries and an `add` method is defined within the function export. 

I would be willing to take this on and submit a PR, if that's alright!

**Comment by sindresorhus** [comment]
Sure, good idea, but I think the two open PRs should be merged first.

Would you be able to help review https://github.com/sindresorhus/pretty-ms/pull/25?

**Comment by sindresorhus** [comment]
This can now be done if you're still interested @kolyaventuri :)

**Comment by kolyaventuri** [comment]
I'll take a stab at it!

**Comment by sindresorhus** [comment]
@kolyaventuri Still interested?

**Comment by kolyaventuri** [comment]
@sindresorhus hi! Yes, absolutely. Apologies on never getting back to this :joy:

**Comment by sindresorhus** [comment]
Bump :)
