### ISSUE TITLE
Package fails to minify

### ISSUE THREAD

**Issue by danias** [sindresorhus/pretty-ms#31]
Failed to minify the code from this file: 

 	./node_modules/pretty-ms/index.js:4 

Facebook recommends to publish code on npm as ES5 at least for a few more years.

Read more here: http://bit.ly/2tRViJ9

**Comment by danias** [comment]
Actually it is (also) a parse-ms issue

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
