### ISSUE TITLE
Improve accuracy

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/pretty-ms#36]
I'm using this library in another library for running benchmarks, and I need 2 features out of `pretty-ms`:

- **Precision**: I need the formatted time to be reasonably accurate. 
- **Cleaness**: At the same time I don't need a verbose formatted time, e.g. if something takes 200ms I don't care how many extra μs it also takes.

I can get a clean output by setting `compact: true`, but then I can't get reasonable precision, as for example the following happens:

- 501ms gets rounded up to 1s, which gives an error of ~100%.
- 1.49s gets rounded up to 1s, which gives an error of ~33%.

I think a possible solution to this would be to avoid overriding `secondsDecimalDigits` and `millisecondsDecimalDigits` when setting `compact: true`.

this may not solve the issue completely though, as for instance I imagine minutes would be rounded up too and I see no `minutesDecimalDigits` option, so perhaps a more general `decimalDigits` option should be used instead?

**Comment by fabiospampinato** [comment]
Also displaying `50ms` rather than `0.5s` would be cleaner IMHO.

**Comment by fabiospampinato** [comment]
On a second thought I think a better and more general solution would be to add a `maxRoundingDelta` option, which will tell how many percentage points the rounded number can deviate from the original number, so for instance if it's set to `10` rounding will only occur if the rounded number will be at most 10% higher/lower than the original number, so for instance 950ms will be rounded to 1s, but 900ms will remain 900ms. By default it should be set to `Infinity` for backwards compatibility.

**Comment by sindresorhus** [comment]
> Also displaying 500ms rather than 0.5s would be cleaner IMHO.

It already does that: https://github.com/sindresorhus/pretty-ms/blob/37cf0a9b8a458a416642fd4756e65d74a7ca2f51/test.js#L7

**Comment by sindresorhus** [comment]
I don't think `maxRoundingDelta` will be useful for other use-cases than yours, so I would try to think of some different solutions. Maybe `{prioritizeAccuracy: true}` or something.

**Comment by fabiospampinato** [comment]
> It already does that:

Right, I don't remember why I wrote that then 🤔 

> Maybe {prioritizeAccuracy: true} or something.

But accuracy to what degree? Like probably I want 990ms to be rounded up to 1s but I don't want 501ms to be rounded up to 1s too, or maybe I want 990.43ms to be rounded up to 990ms rather than 1s.

> I don't think maxRoundingDelta will be useful for other use-cases than yours

I see it as a more powerful/less friendly version of `prioritizeAccuracy`, it solve the issue that numbers may get rounded up so much that they become kind of useless when accuracy is important. I'm not sure many people would use it, but does it matter? Like would it be better to fork this library just for this use case?

**Comment by villebro** [comment]
@fabiospampinato in the current version seconds are never rounded up - if precision is 0 decimals and 9.999 seconds has elapsed, `pretty-ms` will return `9s`. This is to make sure we don't have any truncated seconds: if we were rounding 0.5s to 1s, the 0th second would only display 0s between 0-0.5s. See the tests here:
https://github.com/sindresorhus/pretty-ms/blob/eda21362097d47ab309dca8cf07dc79b25fb0efa/test.js#L250-L254

As the original issue no longer applies, I suggest closing this issue, unless there is a need to introduce a `roundUp` flag to restore the old behavior.
