### ISSUE TITLE
Rounding inconsistency

### ISSUE THREAD

**Issue by villebro** [sindresorhus/pretty-ms#38]
When formatting 11999 milliseconds using default options, the result is `1m 60s` (should obviously be `2m`). Looking at the unit tests I also didn't quite understand why seconds round down

```js
	t.is(prettyMilliseconds(33333, {secondsDecimalDigits: 0}), '33s');
```

but milliseconds round up:

```js
	t.is(prettyMilliseconds(33.333, {millisecondsDecimalDigits: 0}), '34ms');
```

Is there some reason why seconds round as we expect them to (mathematically), but milliseconds seem to round up?

**Comment by sindresorhus** [comment]
> When formatting 11999 milliseconds using default options, the result is 1m 60s (should obviously be 2m)

Good catch.

> Is there some reason why seconds round as we expect them to (mathematically), but milliseconds seem to round up?

Not that I can think of. It should really use `Math.round()` instead of `Match.ceil()`.
