### ISSUE TITLE
Help with keepDecimalsOnWholeSeconds

### ISSUE THREAD

**Issue by AwesomeStickz** [sindresorhus/pretty-ms#43]
I tried to do like this 
prettyms(22200526, { keepDecimalsOnWholeSeconds: true })

From what I understood, it should actually return something like this 6h 10m 1s or 6h 10m but every time it returns 6h 10m 0.5s if that keepDecimalsOnWholeSeconds option shows milli seconds too, what option should I use to round it

**Comment by sindresorhus** [comment]
From the docs:

> Keep milliseconds on whole seconds: 13s → 13.0s.
> Useful when you are showing a number of seconds spent on an operation and don't want the width of the output to change when hitting a whole number.

It preserves the milliseconds part even when it's zero. It doesn't round anything.

I don't think what you're asking is currently possible.

**Comment by AwesomeStickz** [comment]
Oh ok
