### ISSUE TITLE
no decimal points

### ISSUE THREAD

**Issue by coldpour** [sindresorhus/pretty-ms#5]
hey,

i was looking to write a small lib to do exactly what yours does, except that i don't want to see the partial seconds. would you mind creating an option for that?

thanks,
coldpour

**Comment by sindresorhus** [comment]
Sure. Mind sharing your use-case?

**Comment by coldpour** [comment]
Yea, I'm working on a Jenkins build light monitor and each build has a
duration property in ms that I'd like to display like "3m 2s". The extra
fidelity of a partial second isn't useful when looking at a build's
duration. I will also use this same display for elapsed time when a build
is running, like "1m 39s | 3m 2s", but i would just invoke your lib a
second time for that.

You can see my code so far at http://github.com/coldpour/jenkins-build-light
