### ISSUE TITLE
Raising exception when using with setInterval

### ISSUE THREAD

**Issue by harinath9732** [sindresorhus/pretty-ms#51]
Objective: Trying to pretty-ms the seconds received. I am calling a function inside setInterval. Due to this exception is being raised. 
IsFinite check is there from what i understand. Can anything be done for this?

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
