### ISSUE TITLE
Sub 1000ms, with secondsDecimalDigits set to 0, shows ms

### ISSUE THREAD

**Issue by Mageer** [sindresorhus/pretty-ms#52]
**Reproducible example**:
```  JavaScript
import prettyMilliseconds from 'pretty-ms';
const timeStamp = prettyMilliseconds(999, {
  secondsDecimalDigits: 0,
  colonNotation: true,
});
console.log(timeStamp);
```
**Expected**: 0:00
**Result**: 0:00:999

This appears to happen for any sub 1000ms input. 

**Setup**: pretty-ms(v7.0.0), ReactJS (v16.13.1) in development mode running in Google Chrome (v85.0.4183.102)

**Comment by sindresorhus** [comment]
// @villebro

**Comment by villebro** [comment]
Thanks for raising the issue @Mageer and the ping @sindresorhus , I will look into this shortly.

**Comment by villebro** [comment]
Reproduced the error, what a weird bug!
