### ISSUE TITLE
Support negative milliseconds 

### ISSUE THREAD

**Issue by ASaiAnudeep** [sindresorhus/pretty-ms#59]
I have observed that negative milliseconds are not parsed as expected. For example

```js
var prettyMs = require("pretty-ms@7.0.0")

prettyMs(13370); // 13.3s
prettyMs(-13370); // -13s -370ms
```

**Expected**: `-13.3s`
**Actual**: `-13s -370ms`

**Comment by sindresorhus** [comment]
Good catch 👍
