### ISSUE TITLE
TypeError: prettyMilliseconds is not a function

### ISSUE THREAD

**Issue by Jeremyop** [sindresorhus/pretty-ms#61]
/home/runner/ENC/commands/work.js:30
                        .setDescription(`⌛ You can work again in **\`${prettyMilliseconds(userData.cooldowns.work - Date.now(), { verbose: true, secondsDecimalDigits: 0 })}\`**`)
                                                                       ^

TypeError: prettyMilliseconds is not a function
    at Object.run (/home/runner/ENC/commands/work.js:30:72)
   
    
    
    Here is the part of code
    
    
const { SlashCommandBuilder } = require("@discordjs/builders")
const { MessageEmbed } = require("discord.js")
const { User } = require("../utils/schemas")
const prettyMilliseconds = import('pretty-ms');

const jobs = [
    "👮 Police Officer"
]

module.exports = {
    data: new SlashCommandBuilder()
        .setName("work")
        .setDescription("Work to earn money"),
    run: async (interaction) => {
        const user = interaction.member.user
        const userData = await User.findOne({ id: user.id }) || new User({ id: user.id })

        if (userData.cooldowns.work > Date.now())
            return interaction.reply({
                embeds: [
                    new MessageEmbed()
                        .setColor("YELLOW")
                        .setDescription(`⌛ You can work again in **\`${prettyMilliseconds(userData.cooldowns.work - Date.now(), { verbose: true, secondsDecimalDigits: 0 })}\`**`)
                ],
                ephemeral: true
            })

        const amount = Math.floor(Math.random() * (100 - 10 + 1)) + 10
        const job = jobs[Math.floor(Math.random() * jobs.length)]

        userData.wallet += amount
        userData.cooldowns.work = Date.now() + (1000 * 60 * 60)
        userData.save()

        const workEmbed = new MessageEmbed()
            .setDescription(`You worked as a **\` ${job} \`** and earned \` ${amount} 🪙 \``)
            .setColor("YELLOW")

        return interaction.reply({ embeds: [workEmbed] })

    }
}

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
