### ISSUE TITLE
A verbose option?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/pretty-ms#7]
@sindresorhus 
In places where a verbose display is required, I would like something like : -
```js
prettyMs(1337, {verbose: true});
// => 1.3 seconds
// => instead of `1.3s`

prettyMs(1337000000, {verbose: true});
//=> '15 days 11 hours 23 minutes 20 seconds'
```

I would be happy to submit a patch, if you are interested in this too?

**Comment by sindresorhus** [comment]
:+1:
